name: ecommerce_app_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.19.0
  shared_preferences: ^2.1.0
  dotted_line: ^3.2.2
  provider: ^6.0.5
  path: ^1.8.2
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
